# Generated by Django 3.1.7 on 2021-03-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HW', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='file',
            new_name='ans_file',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='ans_title',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='title',
            new_name='hw_title',
        ),
    ]
