# Generated by Django 3.1.7 on 2021-03-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW', '0002_auto_20210307_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
